name: Release Derper

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      release-tag-name:
        required: true
        type: string
      release-image:
        required: true
        type: string
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'tailscale/tailscale'
          ref: ${{ inputs.ref }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Release Cli
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "Mmx233/GoReleaseCli"
          latest: true
          fileName: 'release_linux_amd64.tar.gz'
          extract: true
          out-file-path: './build/'

      - name: Build Binary
        run: ./build/release ./cmd/derper -c tar.gz  --extra-arches --output build/output

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release-tag-name }}
          files: build/output/*.tar.gz

  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'tailscale/tailscale'
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Release Cli
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "Mmx233/GoReleaseCli"
          latest: true
          fileName: 'release_linux_amd64.tar.gz'
          extract: true
          out-file-path: './build/'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.release-image }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build Binary
        run: |
          ./build/release ./cmd/derper --platforms linux/amd64,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x --divider "/" --output-format post --output build/output
          ./build/release ./cmd/derper --platforms linux/arm --extra-arches  --divider "/" --output-format post --output build/output --disable-auto-clean

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.derper
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/riscv64,linux/s390x